create table notification(
                         id integer generated by default as identity primary key,
                         email varchar NOT NULL ,
                         topic varchar not null ,
                         send_message varchar,
                         creation_date timestamp,
                         is_sent boolean
);
