create table scheduled_notifications(
                             id integer generated by default as identity primary key,
                             topic varchar not null ,
                             send_message varchar,
                             start_time_for_search timestamp,
                             end_time_for_search timestamp,
                             scheduled_time TIMESTAMP NOT NULL,
                             creation_date timestamp
);